application: edge-new
version: v0-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- name: lxml
  version: "2.3"
